#ifndef FIFTYONE_DEGREES_SYNONYM_IPI_INCLUDED
#define FIFTYONE_DEGREES_SYNONYM_IPI_INCLUDED

#include "ipi.h"
#include "common-cxx/fiftyone.h"

// Data types
MAP_TYPE(ProfilePercentage)
MAP_TYPE(ResultIpi)
MAP_TYPE(ResultsIpi)
MAP_TYPE(ResultIpiArray)
MAP_TYPE(ConfigIpi)
MAP_TYPE(DataSetIpi)
MAP_TYPE(DataSetIpiHeader)
MAP_TYPE(ProfileCombination)
MAP_TYPE(Ipv4Range)
MAP_TYPE(Ipv6Range)

// Methods
#define ResultsIpiCreate fiftyoneDegreesResultsIpiCreate
#define ResultsIpiFree fiftyoneDegreesResultsIpiFree
#define ResultsIpiFromIpAddress fiftyoneDegreesResultsIpiFromIpAddress
#define ResultsIpiFromIpAddressString fiftyoneDegreesResultsIpiFromIpAddressString
#define ResultsIpiFromEvidence fiftyoneDegreesResultsIpiFromEvidence
#define ResultsIpiGetValues fiftyoneDegreesResultsIpiGetValues
#define ResultsIpiGetValuesString fiftyoneDegreesResultsIpiGetValuesString
#define ResultsIpiGetValuesStringByRequiredPropertyIndex fiftyoneDegreesResultsIpiGetValuesStringByRequiredPropertyIndex
#define ResultsIpiGetHasValues fiftyoneDegreesResultsIpiGetHasValues
#define ResultsIpiGetNoValueReason fiftyoneDegreesResultsIpiGetNoValueReason
#define ResultsIpiGetNoValueReasonMessage fiftyoneDegreesResultsIpiGetNoValueReasonMessage
#define IpiInitManagerFromFile fiftyoneDegreesIpiInitManagerFromFile
#define IpiInitManagerFromMemory fiftyoneDegreesIpiInitManagerFromMemory
#define DataSetIpiGet fiftyoneDegreesDataSetIpiGet
#define DataSetIpiRelease fiftyoneDegreesDataSetIpiRelease
#define IpiReloadManagerFromOriginalFile fiftyoneDegreesIpiReloadManagerFromOriginalFile
#define IpiReloadManagerFromFile fiftyoneDegreesIpiReloadManagerFromFile
#define IpiReloadManagerFromMemory fiftyoneDegreesIpiReloadManagerFromMemory
#define IpiGetNetworkIdFromResult fiftyoneDegreesIpiGetNetworkIdFromResult
#define IpiGetNetworkIdFromResults fiftyoneDegreesIpiGetNetworkIdFromResults
#define IpiGetCoordinate fiftyoneDegreesIpiGetCoordinate
#define IpiGetIpRangeAsString fiftyoneDegreesIpiGetIpRangeAsString
#define IpiIterateProfilesForPropertyAndValue fiftyoneDegreesIpiIterateProfilesForPropertyAndValue

// Config
#define IpiInMemoryConfig fiftyoneDegreesIpiInMemoryConfig /**< Synonym for #fiftyoneDegreesIpiInMemoryConfig config. */
#define IpiHighPerformanceConfig fiftyoneDegreesIpiHighPerformanceConfig /**< Synonym for #fiftyoneDegreesIpiHighPerformanceConfig config. */
#define IpiLowMemoryConfig fiftyoneDegreesIpiLowMemoryConfig /**< Synonym for #fiftyoneDegreesIpiLowMemoryConfig config. */
#define IpiBalancedConfig fiftyoneDegreesIpiBalancedConfig /**< Synonym for #fiftyoneDegreesIpiBalancedConfig config. */
#define IpiBalancedTempConfig fiftyoneDegreesIpiBalancedTempConfig /**< Synonym for #fiftyoneDegreesIpiBalancedTempConfig config. */
#define IpiDefaultConfig fiftyoneDegreesIpiDefaultConfig /**< Synonym for #fiftyoneDegreesIpiDefaultConfig config. */

#endif